### ISSUE TITLE
ECT is a unconditional model?

### ISSUE THREAD

**Issue by 2019211753** [locuslab/ect#1]
I'm considering whether it's possible to modify the ECT model to generate samples based on text conditions.
Additionally, is it possible to change the image mode to another mode? such as 3D human skeleton.

**Comment by Gsunshine** [comment]
Hi @2019211753 ,

Thanks for your interest in ECT! ECT can also work in conditional settings. We tested it using CIFAR10 and ImageNet. I think it works well for class conditional settings. Indeed, conditional information even boosts and eases learning, according to my observations. 

You are welcome to try & test other modalities and conditioning. But do pay attention to monitor and cope with the "[curse of consistency](https://www.notion.so/gsunshine/Consistency-Models-Made-Easy-954205c0b4a24c009f78719f43b419cc?pvs=4#755bb74b62db41e0b3ce4ca32be8dde5)"!

Thanks,
Zhengyang

**Comment by 2019211753** [comment]
Hi @Gsunshine ,
Thank you for your response! I have a few additional questions. Could you please provide guidance on how to set up the ECT environment? Also, how should I proceed to run it? I encountered an error when attempting to execute bash run_ecm.sh 3 12000 --desc bs128.200k: the error message was "run_ecm.sh: line 2: torchrun: command not found."

Furthermore, could you clarify if ECM and ECT refer to the same thing? Apologies if my lack of knowledge has led to too many questions.

**Comment by Gsunshine** [comment]
Hi @2019211753 ,

We've updated the environment setup. I suggest setting the number of GPUs as the power of 2. You need a GPU machine with at least 1 A6000 GPU or equivalent. Set up your environment using `conda` as in README.

Sorry for the confusion. We denote the technique from [our blog post](https://gsunshine.notion.site/Consistency-Models-Made-Easy-954205c0b4a24c009f78719f43b419cc?pvs=4) as Easy Consistency Tuning (ECT), while the models trained by ECT as ECM. In most case, you can refer it as ECT.

Best luck with your journey!

Zhengyang

**Comment by 2019211753** [comment]
> Hi @2019211753 ,
> 
> We've updated the environment setup. I suggest setting the number of GPUs as the power of 2. You need a GPU machine with at least 1 A6000 GPU or equivalent. Set up your environment using `conda` as in README.
> 
> Sorry for the confusion. We denote the technique from [our blog post](https://gsunshine.notion.site/Consistency-Models-Made-Easy-954205c0b4a24c009f78719f43b419cc?pvs=4) as Easy Consistency Tuning (ECT), while the models trained by ECT as ECM. In most case, you can refer it as ECT.
> 
> Best luck with your journey!
> 
> Zhengyang

Thanks for your reply. It helps me a lot.
