### ISSUE TITLE
How to control the sampling steps through “intermediate t”？

### ISSUE THREAD

**Issue by wangyp33** [locuslab/ect#11]
Hello，I am very interested in the CM and your work. 
Could you please advise me on how to adjust the parameter 't' to control the sampling steps? I observed that you set theparameter '**mid_t =0.821**'  for 2-steps sampling in CIFAR10. 
If I wish to generate one step or multiple steps, how should I adjust the value of 'mid_t' ?  maybe I miss something of your paper，please explain briefly.Thank you very much！

**Comment by wangyp33** [comment]
Additionally,how to fine-tuing the weighting ¯w(t) as the Table 3 in Appendix B

**Comment by Gsunshine** [comment]
Hi @wangyp33 ,

Thanks for your interest in ECT!

For intermediate timesteps, It's a very good question and I think also an open research problem. I don't have a manual for it. Here are some thoughts. You can treat it as an optimization problem, maximizing the sample quality (in terms of many metrics) w.r.t these sampling schedules. I encourage you to explore more!

Regarding weightings, you could write the timestep weighting by yourself. Typically only 1 line. For example,

```
wt = (t ** 2 + self.sigma_data ** 2) / (t * self.sigma_data) ** 2
```

Make sure your `wt` has the same shape as your `loss` by `assert wt.ndim == loss.ndim`. If not, reshape it.

Good luck with your journey! 

Thanks,
Zhengyang

**Comment by wangyp33** [comment]
Thank you for your reply!
