### ISSUE TITLE
Inference/sampling on model's training output .pt

### ISSUE THREAD

**Issue by ToolKami** [locuslab/ect#16]
Hi, thanks for your great work on this.

As above, what would be the easiest or best way to sample/infer from model's output.

Would it be possible to run it through https://huggingface.co/docs/diffusers/main/en/api/pipelines/consistency_models?

**Comment by Gsunshine** [comment]
Hi @ToolKami ,

I believe a simpler way currently is to reuse this codebase. For example, you can load a checkpoint and run inference like [here](https://github.com/locuslab/ect/blob/4311059770f54821d151a9b0e1f76770a5f3930e/training/ct_training_loop.py#L341). Define a script to load the model and run the inference via the `generator_fn`.

Thanks for the comments! I'll also check if we can support the `diffuser` interface!

Thanks,
Zhengyang
