### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by 2019211753** [locuslab/ect#2]
After executing  `run_ecm.sh 2 12000 --desc bs128.200k`, at the end of the command 'run_ecm.sh 2 12000 --desc bs128.200k', errors occurred at the end of the command:
```bash
Save the latest checkpoint at 002000 img...
Exporting sample images...
Evaluating models...
{"results": {"fid50k_full": 3.8353654222056845}, "metric": "fid50k_full", "total_time": 58.53903794288635, "total_time_str": "59s", "num_gpus": 2, "snapshot_pkl": "../../network-snapshot-002000.pkl", "timestamp": 1714338724.8849282}
Exporting final sample images...
Evaluating few-step generation...
{"results": {"fid50k_full": 2.1152479856781503}, "metric": "fid50k_full", "total_time": 84.45072746276855, "total_time_str": "1m 24s", "num_gpus": 2, "snapshot_pkl": "../../network-snapshot-latest.pkl", "timestamp": 1714338809.891528}
{"results": {"fid50k_full": 2.0880729855906393}, "metric": "fid50k_full", "total_time": 84.58539080619812, "total_time_str": "1m 25s", "num_gpus": 2, "snapshot_pkl": "../../network-snapshot-latest.pkl", "timestamp": 1714338894.4783652}
{"results": {"fid50k_full": 2.09729291301326}, "metric": "fid50k_full", "total_time": 84.62678050994873, "total_time_str": "1m 25s", "num_gpus": 2, "snapshot_pkl": "../../network-snapshot-latest.pkl", "timestamp": 1714338979.1066105}

Exiting...
run_ecm.sh: line 8: $'{@:3}\r': command not found
```
I use cifar-10 datasets to train ecm.

**Comment by Gsunshine** [comment]
Hi @2019211753 ,

Thanks for sharing this. I reran my local script but did not see this error. 
`run_ecm.sh: line 8: $'{@:3}\r': command not found`

Can you check your script to see if the `\` in line 7 is missing? It looks like, when missing this `\`, `$'{@:3}\r'` was treated as a single command after the main script (its purpose is to override the keyword arguments.)

The results look pretty good, even slightly better than reported in the blog (median). ;D
I believe ECT is highly reliable and easy to reproduce, yet effective. 

Feel free to try more. Enjoy.

Zhengyang
