### ISSUE TITLE
Will you release an arxiv paper?

### ISSUE THREAD

**Issue by aiihn** [locuslab/ect#3]
Thanks for your great work! Will you release an arxiv paper? Looking forward to it.

**Comment by Gsunshine** [comment]
Hi @aiihn ,

Thanks for your interest! Yep, we will release a research paper soon! 
Feel free to try ECT! :D 

Thanks,
Zhengyang

**Comment by 2019211753** [comment]
I just find that [ECT](https://arxiv.org/abs/2406.14548) has been released on arxiv yesterday😄
