### ISSUE TITLE
Try on Stable Diffusion?

### ISSUE THREAD

**Issue by XinYu-Andy** [locuslab/ect#6]
Hi,
Very excellent work!
I am wondering if you have conducted some initial experiments on Stable Diffusion? That would be a huge thing if this method can work.

**Comment by Gsunshine** [comment]
Hi @XinYu-Andy ,

Thank you for your interest in ECT! Before trying on SD, guidance & CFG needs to be handled particularly. 
We will share more progress later! 

Best,
Zhengyang

**Comment by yuanzhi-zhu** [comment]
Hi @Gsunshine, how is it going with the SD exprs?
