### ISSUE TITLE
Configs for NCSN++

### ISSUE THREAD

**Issue by sobieskibj** [locuslab/ect#7]
Hi,
excellent work! I went through the training code and noticed that, besides the DDPM++ architecture mentioned in the paper, there is also the NCSN++ network. I am interested in using ECT with it, since there are some checkpoints from Yang Song's _Score-Based Generative Modeling through Stochastic Differential Equations_ paper trained on other datasets. Do you have any recommended configs (hyperparameters) from which I should start the fine-tuning? Thanks in advance!

**Comment by Gsunshine** [comment]
Hi @sobieskibj,

Thank you for your interest in ECT! You can use the same configurations from DDPM++ to tune NCSN++. There shouldn't be significant differences between them. I suggest using the current code base, as EDM has also provided checkpoints that utilize the VE forward process. Please refer to the pretrained  [checkpoints](https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/).

From my empirical observations, NCSN++ appears to perform better in terms of FID, while DDPM++ has produced stronger results using $\mathrm{FD}_{\text{DINOv2}}$. Both are very good models!

Feel free to reach out if you have any questions. Best of luck on your journey!

Warm regards,
Zhengyang

**Comment by sobieskibj** [comment]
Thank you for the response :) My main reason behind trying to use the checkpoints from the [Score SDE repo](https://github.com/yang-song/score_sde) is that they trained their models on e.g. CelebA-HQ with 256x256 resolution, which is not the case for EDM. Should I expect that their checkpoints will work with the current state of ECT if I match the hyperparameters correctly (e.g. the obvious ones like number of blocks in the UNet and so on) for the NCSN++ (SongUNet) from your codebase?
